config/routes.rb
Rails.application.routes.draw do
  resources :new_musics
  get 'home/index'
  get 'welcome/index'
  post 'home/create'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
end

app/models/new_music.rb
class NewMusic < ApplicationRecord
end

app/models/simple_music.rb
class SimpleMusic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to new_new_music_path
    #@music = 
    # @simple_music = SimpleMusic.new
  end

  def create
    # puts " "
    # puts " "
    # puts "START ========================="
    # puts params[:simple_music]
    # puts "END ========================="
    # #debug(params)
    # @simple_music = SimpleMusic.new(params[:simple_music])

    # respond_to do |format|
    #   if @simple_music.save
    #     format.html { redirect_to home_index_path, notice: 'Simple music was successfully created.' }
    #     format.json { render :index, status: :created, location: @simple_music }
    #   else
    #     format.html { render :index }
    #     format.json { render json: @simple_music.errors, status: :unprocessable_entity }
    #   end
    # end
  end

end

app/controllers/new_musics_controller.rb
class NewMusicsController < ApplicationController
  before_action :set_new_music, only: [:show, :edit, :update, :destroy]

  # GET /new_musics
  # GET /new_musics.json
  def index
    @new_musics = NewMusic.all
  end

  # GET /new_musics/1
  # GET /new_musics/1.json
  def show
  end

  # GET /new_musics/new
  def new
    @new_music = NewMusic.new
  end

  # GET /new_musics/1/edit
  def edit
  end

  # POST /new_musics
  # POST /new_musics.json
  def create
    @new_music = NewMusic.new(new_music_params)

    respond_to do |format|
      if @new_music.save
        format.html { redirect_to @new_music, notice: 'New music was successfully created.' }
        format.json { render :show, status: :created, location: @new_music }
      else
        format.html { render :new }
        format.json { render json: @new_music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /new_musics/1
  # PATCH/PUT /new_musics/1.json
  def update
    respond_to do |format|
      if @new_music.update(new_music_params)
        format.html { redirect_to @new_music, notice: 'New music was successfully updated.' }
        format.json { render :show, status: :ok, location: @new_music }
      else
        format.html { render :edit }
        format.json { render json: @new_music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /new_musics/1
  # DELETE /new_musics/1.json
  def destroy
    @new_music.destroy
    respond_to do |format|
      format.html { redirect_to new_musics_url, notice: 'New music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_new_music
      @new_music = NewMusic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_music_params
      params.require(:new_music).permit(:artist, :genre, :song, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_musics_helper.rb
module NewMusicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h1 class="red"> Welcome to Home Page</h1>
<p>What's your favorite music?</p>

 <%= simple_form_for @simple_music, url: home_create_path(@simple_music) do |f| %>
  <%= f.input :artist %>
  <%= f.input :song %>
  <%= f.input :genre %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/new_musics/_form.html.erb
<%= simple_form_for(@new_music) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :artist %>
    <%= f.input :genre %>
    <%= f.input :song %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/new_musics/edit.html.erb
<h1>Editing New Music</h1>

<%= render 'form', new_music: @new_music %>

<%= link_to 'Show', @new_music %> |
<%= link_to 'Back', new_musics_path %>

app/views/new_musics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>New Musics</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Genre</th>
      <th>Song</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @new_musics.each do |new_music| %>
      <tr>
        <td><%= new_music.artist %></td>
        <td><%= new_music.genre %></td>
        <td><%= new_music.song %></td>
        <td><%= new_music.description %></td>
        <td><%= link_to 'Show', new_music %></td>
        <td><%= link_to 'Edit', edit_new_music_path(new_music) %></td>
        <td><%= link_to 'Destroy', new_music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New New Music', new_new_music_path %>

app/views/new_musics/new.html.erb
<h1>New New Music</h1>

<%= render 'form', new_music: @new_music %>

<%= link_to 'Back', new_musics_path %>

app/views/new_musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @new_music.artist %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @new_music.genre %>
</p>

<p>
  <strong>Song:</strong>
  <%= @new_music.song %>
</p>

<p>
  <strong>Description:</strong>
  <%= @new_music.description %>
</p>

<%= link_to 'Edit', edit_new_music_path(@new_music) %> |
<%= link_to 'Back', new_musics_path %>

app/views/welcome/index.html.erb
<h1 class="red">Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>